"""empty message

Revision ID: 4a8437fd6a70
Revises: f7c4d5bf207c
Create Date: 2023-03-09 00:49:17.918128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4a8437fd6a70"
down_revision = "f7c4d5bf207c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
