"""empty message

Revision ID: 60ff0a59d5c3
Revises: 996ab4e7f866
Create Date: 2023-03-10 19:14:56.417258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ff0a59d5c3'
down_revision = '996ab4e7f866'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_repeat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_repeat', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
