"""empty message

Revision ID: 73d01981f14a
Revises: 785b5da40e00
Create Date: 2023-03-06 16:17:25.058942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73d01981f14a"
down_revision = "785b5da40e00"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cats", "foo")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cats", sa.Column("foo", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
