"""create_cats_table

Revision ID: 9eefca109345
Revises: 
Create Date: 2023-03-06 16:10:21.063383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9eefca109345"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("breed", sa.String(), nullable=True),
        sa.Column("age", sa.String(), nullable=True),
        sa.Column("size", sa.String(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cats_breed"), "cats", ["breed"], unique=False)
    op.create_index(op.f("ix_cats_id"), "cats", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cats_id"), table_name="cats")
    op.drop_index(op.f("ix_cats_breed"), table_name="cats")
    op.drop_table("cats")
    # ### end Alembic commands ###
