"""empty message

Revision ID: ac6c8e48e0e4
Revises: b0a6081df68c
Create Date: 2023-03-08 23:49:05.410368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ac6c8e48e0e4"
down_revision = "b0a6081df68c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cats", "foo")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cats", sa.Column("foo", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
