"""empty message

Revision ID: b0a6081df68c
Revises: 73d01981f14a
Create Date: 2023-03-08 23:48:36.875968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b0a6081df68c"
down_revision = "73d01981f14a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cats", sa.Column("foo", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cats", "foo")
    # ### end Alembic commands ###
