"""empty message

Revision ID: d8fff43b2115
Revises: 4a8437fd6a70
Create Date: 2023-03-09 00:49:57.699279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d8fff43b2115"
down_revision = "4a8437fd6a70"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dogs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("breed", sa.String(), nullable=True),
        sa.Column("origin", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("height", sa.String(), nullable=True),
        sa.Column("eyes_color", sa.String(), nullable=True),
        sa.Column("longevity", sa.String(), nullable=True),
        sa.Column("character", sa.String(), nullable=True),
        sa.Column("health_problems", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dogs_id"), "dogs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dogs_id"), table_name="dogs")
    op.drop_table("dogs")
    # ### end Alembic commands ###
